name: pvnet
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python==3.7
  - pytorch==1.1.0
  - torchvision==0.2.1
  - fastprogress
  - fastai
  - jupyter
  - scipy==1.2.1
  - matplotlib==3.0.2
  - transforms3d==0.3.1
  - setuptools==39.1.0
  - cffi==1.11.5
  - numpy==1.16.4
  - cython==0.29.14
  - trimesh
  - pip
  - pip:
      - plyfile==0.6
      - opencv_contrib_python==3.4.2.17
      - lmdb==0.94
      - glumpy==1.0.6
      - scikit_image==0.14.2
      - easydict==1.7
      - tqdm==4.28.1
      - yacs==0.1.4
      - pycocotools==2.0.0
      - scikit-learn
      - PyOpenGL==3.1.1a1
      - ipdb==0.11
      - cyglfw3==3.1.0.2
      - pyassimp==3.3
      - progressbar==2.5
      - open3d-python==0.5.0.0
      - plotly==4.8.2
      - tikzplotlib==0.9.6
      - tensorboardX==1.2
