# wait
model: 'custom'
model_dir: 'data/model'
network: 'res'
heads: ''
task: 'pvnet'
gpus: [0]
resume: True
eval_ep: 5
monitor: True

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 240
    milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
    gamma: 0.5
    batch_size: 8
    dataset: 'SynColibriV1_Train'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
    batch_sampler: 'image_size'
test:
    dataset: 'SynColibriV1_Val'
    batch_size: 8
    batch_sampler: 'image_size'
    un_pnp: True
